# Build the application
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./ 

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Copy only the necessary files from the builder stage
COPY /src/config.json ./dist/

# Build the application
RUN pnpm run compile

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]
